// Generated by Akira v0.0.1
(function () {
  var CallExpression, Identifier, MemberExpression, ast, IdenThen, Do;
  CallExpression = require('ast/CallExpression');
  Identifier = require('ast/Identifier');
  MemberExpression = require('ast/MemberExpression');
  ast = require('ast');
  IdenThen = Identifier('then');
  Do = function () {
    var _$Class;
    _$Class = function (call, f) {
      this.call = call;
      this.f = f;
      this;
    };
    _$Class.prototype.compile = function (context) {
      var call, f;
      call = ast(this.call, context);
      f = ast(this.f, context);
      return CallExpression(MemberExpression(call, IdenThen), [f]);
    };
    return _$Class;
  }.apply(this, arguments);
  return module.exports = Do;
}());