// Generated by Akira v0.0.1
(function () {
  var path, r;
  path = require('path');
  r = function (m) {
    return require(path.join(__dirname, m.toLowerCase()));
  };
  module.exports = {
    Access: r('access'),
    Arguments: r('arguments'),
    Assignment: r('assignment'),
    Async: r('async'),
    Await: r('await'),
    Call: r('call'),
    Class: r('class'),
    ClassMethod: r('classmethod'),
    Cloning: r('cloning'),
    Compare: r('compare'),
    Cond: r('cond'),
    Declaration: r('declaration'),
    Do: r('do'),
    Exception: r('exception'),
    ExceptionGuard: r('exception-guard'),
    Export: r('export'),
    Evaluate: r('evaluate'),
    If: r('if'),
    Identifier: r('identifier'),
    Instantiate: r('instantiate'),
    Import: r('import'),
    Let: r('let'),
    L: r('line'),
    Literal: r('literal'),
    Logic: r('logic'),
    Macro: r('macro'),
    Map: r('map'),
    MaybeSeq: r('maybeseq'),
    Nodes: r('nodes'),
    Operation: r('operation'),
    Pattern: r('pattern'),
    Pipeline: r('pipeline'),
    Recur: r('recur'),
    Type: r('type'),
    TypeAlias: r('typealias'),
    TypeSignature: r('typesignature'),
    Vector: r('vector')
  };
}());