// Generated by Akira v0.0.1
!function() {

var ast, BinaryExpression, Inst;
ast = require('ast');
BinaryExpression = require('ast/BinaryExpression');
Inst = function () {
  var _$Class;
  _$Class = function (a, b) {
    this.a = a;
    this.b = b;
    this;
  };
  _$Class.prototype.compile = function (context) {
    return BinaryExpression('instanceof', ast(this.a, context), ast(this.b, context));
  };
  return _$Class;
}.apply(this, arguments);
return module.exports = Inst;
}();