// Generated by Akira v0.0.1
(function () {
  var ast, Instantiate;
  ast = require('ast');
  Instantiate = function () {
    var _$Class;
    _$Class = function (iden) {
      this.iden = iden;
    };
    _$Class.prototype.compile = function (context) {
      var name;
      name = ast(this.iden, context);
      return {
        type: 'NewExpression',
        callee: name.callee,
        arguments: name.arguments
      };
    };
    return _$Class;
  }.apply(this, arguments);
  module.exports = Instantiate;
}());