// Generated by Akira v0.0.1
!function() {

var Store, ast, Macro;
Store = require('Store');
ast = require('ast');
Macro = function () {
  var _$Class;
  _$Class = function (name, args) {
    this.name = name;
    this.args = args;
    this;
  };
  _$Class.prototype.compile = function (context) {
    var name;
    name = this.name.name;
    Store.macros[name] = ast(this.args, context);
    return [];
  };
  return _$Class;
}.apply(this, arguments);
return module.exports = Macro;
}();